baseURL: 'http://philibert.hugo'
DefaultContentLanguage: en
MetaDataFormat: yaml
title: Regis Philibert
theme: regisphilibert
enableRobotsTXT: true
buildDrafts: false
pygmentsCodefences: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true

related:
  includeNewer: true
  indices:
    - name: tags
      weight: 100
      toLower: true
    - name: date
      weight: 10
      pattern: 2006

blackfriday:
  extensions:
    - hardLineBreak
  hrefTargetBlank: true

outputFormats:
  markdown:
    baseName: markdown
    mediaType: "text/html"
    
taxonomies:
  tag: tags
  category: categories
  project_tag: project_tags

permalinks:
  post: 'blog/:year/:month/:slug/'

params:
  description: I'm a front end dev from MontrÃ©al specialized in Hugo and Wordpress! How can I help?
  author: Regis Philibert
  jobtitle: Front Dev in Montreal
  twitter_handle: regisphilibert
  emotion: thanksgiving
  ajax: false
  env: local
  less: false
  sass: true
  contactFormApi: 'https://api.regisphilibert.com/mail/'
  prism: false
  imagesizes:
    '500': small
    '750': medium
languages:
  en:
    weight: 1
    flag: "ðŸ‡¬ðŸ‡§"
  fr:
    weight: 2
    flag: "ðŸ‡«ðŸ‡·"
    description: Je suis un dev front end de MontrÃ©al spÃ©cialisÃ© dans Hugo et Wordpress! Je peux vous aider?
    jobtitle: Dev Front Ã  MontrÃ©al
    menu:
      mobile:
        - identifier: blog
          name: Blogue
          weight: 4
          url: "/blog"
      desktop:
        - identifier: blog
          name: et mon blogue.
          weight: 3
          url: "/blog"
          pre: Blogue

imaging:
  resampleFilter: box
  quality: 80


