[build]
  publish = "public"
  command = "cd themes/regisphilibert && npm install && grunt production && cd ../.. && hugo --config config.toml,config.netlify.toml"

[context.production.environment]
  HUGO_VERSION = "0.35"
  HUGO_ENV = "netlify"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.35"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.35"